# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in regorusrb.gemspec
gemspec

# These gems are required for local development and testing,
# but won't be included in the published gem
gem "minitest", "~> 5.25"
gem "rake", "~> 13.2"
gem "rake-compiler", "~> 1.2"
gem "rake-compiler-dock", "~> 1.9"
gem "rubocop", "~> 1.73", require: false
gem "rubocop-minitest", "~> 0.37.1", require: false
gem "rubocop-rake", "~> 0.7.1", require: false
