# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in regorusrb.gemspec
gemspec

# These gems are required for local development and testing,
# but won't be included in the published gem
gem "minitest", "~> 6.0"
gem "rake", "~> 13.3"
gem "rake-compiler", "~> 1.3"
gem "rake-compiler-dock", "~> 1.11"
gem "rubocop", "~> 1.84", require: false
gem "rubocop-minitest", "~> 0.39.1", require: false
gem "rubocop-rake", "~> 0.7.1", require: false
