#!/bin/bash
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

set -eo pipefail

if [ -f Cargo.toml ]; then
   # Run precommit checks
   dir=$(dirname "${BASH_SOURCE[0]}")
   "$dir/pre-commit"

   # Ensure that all tests pass
   # Also generate coverage information.
   if [[ "$OSTYPE" == "linux-gnu"* ]]; then
       scripts/coverage
   fi
fi
