#!/bin/bash
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

set -e
rego=$(realpath -e $1)

if [ ! -z  "$2"  ]; then
    input=$(realpath -e $2)
    cargo test analyzer::one_file -- --include-ignored --nocapture "$rego" "$input"
else
    cargo test analyzer::one_file -- --include-ignored --nocapture "$rego"
fi
