name: bindings/csharp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4

      - name: Build Regorus binding
        run: dotnet build /p:Configuration=Release
        working-directory: ./bindings/csharp/Regorus

      # On Linux, build /p:Configuration=Release and pack must be done separately.
      # Otherwise the rust shared library, which is built using a target executed
      # before Compiler, is not packaged into the nuget.
      # This is likely a bug or a subtle difference in behavior of msbuild/dotnet
      # between Windows and Linux.
      - name: Pack Regorus nuget
        run: dotnet pack; unzip -l bin/Release/Regorus*.nupkg
        working-directory: ./bindings/csharp/Regorus
        
      - name: Restore Test App
        run: dotnet restore /p:RestoreSources=./../Regorus/bin/Release
        working-directory: ./bindings/csharp/TestApp

      - name: Build Test App 8.0
        run: dotnet build --framework net8.0
        working-directory: ./bindings/csharp/TestApp

      - name: Run Test App 8.0
        run: dotnet run --framework net8.0
        working-directory: ./bindings/csharp/TestApp
